(function(){
  "use strict";
  var app=document.getElementById("staff-app"),toastEl=document.getElementById("staff-toast"),STORAGE="airesv-babymonster-demo",THEME_STORAGE="airesv-ops-theme";
  var state={view:new URLSearchParams(location.search).get("view")||"dashboard",scanStep:new URLSearchParams(location.search).get("step")||"idle",now:"K1429",filter:"",statusFilter:"all",theme:document.documentElement.dataset.opsTheme||"dark"};
  var sessions=[
    {time:"11:00",label:"上午場",booked:50,checked:46,entered:44,status:"closed"},
    {time:"12:30",label:"午間場",booked:50,checked:48,entered:45,status:"closed"},
    {time:"14:00",label:"午後場",booked:50,checked:38,entered:26,status:"current"},
    {time:"14:30",label:"午後場",booked:47,checked:0,entered:0,status:"next"},
    {time:"15:00",label:"午後場",booked:42,checked:0,entered:0,status:"next"},
    {time:"15:30",label:"午後場",booked:39,checked:0,entered:0,status:"next"}
  ];
  var roster=[
    {code:"KP-816-1429",name:"張語芯",phone:"••• 0188",party:2,slot:"14:00",status:"entered",queue:"K1429"},
    {code:"KP-816-1430",name:"吳凱琳",phone:"••• 2271",party:1,slot:"14:00",status:"checked-in",queue:"K1430"},
    {code:"KP-816-1431",name:"何雨晴",phone:"••• 6630",party:3,slot:"14:00",status:"checked-in",queue:"K1431"},
    {code:"KP-816-1437",name:"林星妍",phone:"••• 5678",party:2,slot:"14:00",status:"reserved",queue:"—"},
    {code:"KP-816-1442",name:"陳品妤",phone:"••• 9112",party:2,slot:"14:00",status:"reserved",queue:"—"},
    {code:"KP-816-1451",name:"王昕安",phone:"••• 3014",party:1,slot:"14:30",status:"reserved",queue:"—"}
  ];
  function stored(){try{return JSON.parse(localStorage.getItem(STORAGE)||"{}");}catch(e){return {};}}
  function persist(patch){var data=Object.assign({},stored(),patch,{updatedAt:Date.now()});localStorage.setItem(STORAGE,JSON.stringify(data));return data;}
  function applyTheme(theme,save){state.theme=theme==="light"?"light":"dark";document.documentElement.dataset.opsTheme=state.theme;document.querySelector('meta[name="theme-color"]').setAttribute("content",state.theme==="light"?"#f5f5f4":"#0c0a09");if(save!==false)try{localStorage.setItem(THEME_STORAGE,state.theme);}catch(e){}}
  function syncThemeControl(){var actions=document.querySelector(".top-actions");if(!actions||actions.querySelector(".theme-toggle"))return;var isLight=state.theme==="light",button=document.createElement("button");button.type="button";button.className="theme-toggle";button.dataset.action="toggle-theme";button.setAttribute("aria-label",isLight?"切換至暗色模式":"切換至亮色模式");button.setAttribute("aria-pressed",String(isLight));button.innerHTML="<span aria-hidden='true'>"+(isLight?"☾":"☀")+"</span><b>"+(isLight?"暗色":"亮色")+"</b>";actions.insertBefore(button,actions.firstChild);}
  function toast(text){toastEl.textContent=text;toastEl.classList.add("show");setTimeout(function(){toastEl.classList.remove("show");},1800);}
  function syncRoster(){var data=stored(),person=roster.filter(function(r){return r.code==="KP-816-1437";})[0];if(data.holder)person.name=data.holder;if(data.companions!==undefined)person.party=Number(data.companions)+1;if(data.status==="checked-in"){person.status="checked-in";person.queue="K1437";}if(data.status==="called"){person.status="called";person.queue="K1437";state.now="K1437";}}
  function art(){return "<div class='bm-art'><b>BM</b><i></i></div>";}
  function layout(content){var nav=[["dashboard","01","總覽"],["sessions","02","場次監測"],["roster","03","預約名單"],["scanner","04","掃描報到"],["queue","05","叫號控制"]];return "<div class='staff-layout'><aside class='staff-sidebar'><a href='./index.html' class='brand-lockup'>"+art()+"<div><strong>AIRESV OPS</strong><span>TDK Culture · Staff</span></div></a><nav class='staff-nav'>"+nav.map(function(n){return "<button class='"+(state.view===n[0]?"active":"")+"' data-view='"+n[0]+"'><i>"+n[1]+"</i><span>"+n[2]+"</span></button>";}).join("")+"</nav><div class='staff-side-bottom'><div class='live-indicator'><span>系統連線正常</span><strong>LIVE · 14:18:22</strong></div><a class='side-link' href='./user.html'>開啟使用者端 ↗</a></div></aside><main class='staff-main'><header class='staff-topbar'><div class='event-crumb'>"+art()+"<div><strong>BABYMONSTER POP-UP STORE</strong><span>2026.08.15 · 新光三越台北南西店 7F</span></div></div><div class='top-actions'><button class='btn btn-dark' data-view='scanner'>＋ 快速掃描</button><div class='staff-account'><div class='staff-avatar'>ML</div><span>入口 A · Mike</span></div></div></header>"+content+"</main></div>";}
  function pageHead(kicker,title,note){return "<div class='page-head'><div><p class='kicker'>"+kicker+"</p><h1>"+title+"</h1></div><p class='head-note'>"+note+"</p></div>";}
  function pill(status){var map={reserved:["pill-gray","已預約"],"checked-in":["pill-green","已報到"],entered:["pill-dark","已入場"],called:["pill-pink","已叫號"],closed:["pill-gray","已結束"],current:["pill-green","進行中"],next:["pill-gray","未開始"]};var m=map[status]||map.reserved;return "<span class='pill "+m[0]+"'>"+m[1]+"</span>";}
  function sessionRows(){return sessions.map(function(s){return "<tr class='"+(s.status==="current"?"current":"")+"'><td><strong>"+s.time+"</strong></td><td>"+s.label+" · 30 分鐘</td><td>"+s.booked+" 人</td><td>"+s.checked+" 人</td><td>"+s.entered+" 人</td><td><div class='capacity'><div class='capacity-track'><i style='width:"+(s.booked/50*100)+"%'></i></div><span>"+s.booked+" / 50</span></div></td><td>"+pill(s.status)+"</td><td><button class='text-btn' data-view='sessions'>查看 →</button></td></tr>";}).join("");}
  function dashboard(){syncRoster();var data=stored(),checked=data.status==="checked-in"||data.status==="called";return layout("<section class='staff-content'>"+pageHead("OPERATIONS OVERVIEW","今日營運總覽","即時掌握每一場預約、報到與實際入場人數；資料示範每 5 秒同步一次。")+"<div class='metric-grid'><article class='metric'><div class='metric-top'><span>今日總預約</span><i>↗</i></div><strong>278</strong><small>6 個場次 · 總容量 300</small></article><article class='metric'><div class='metric-top'><span>已完成報到</span><i>✓</i></div><strong>"+(checked?133:132)+"</strong><small>報到率 47.8%</small></article><article class='metric'><div class='metric-top'><span>已實際入場</span><i>→</i></div><strong>115</strong><small>目前館內 24 人</small></article><article class='metric'><div class='metric-top'><span>異常／人工處理</span><i>!</i></div><strong>4</strong><small>遲到 2 · 重複掃描 1 · 其他 1</small></article></div><div class='dashboard-grid'><article class='panel current-session'><div class='session-status'><span>CURRENT ADMISSION WINDOW</span><b>● OPEN NOW</b></div><h2>14:00—14:30</h2><p>08/15（六）· 下午場 · 入口 A</p><div class='session-numbers'><div><small>本場預約</small><strong>50</strong></div><div><small>已報到</small><strong>"+(checked?39:38)+"</strong></div><div><small>已入場</small><strong>26</strong></div></div></article><article class='panel'><div class='panel-head'><div><h2>最近報到</h2><p>入口 A · 即時紀錄</p></div><button class='panel-link' data-view='roster'>全部名單 →</button></div><div class='recent-list'>"+(checked?"<div class='recent-item'><div class='recent-avatar'>林</div><div><strong>林星妍 · 2 人</strong><span>KP-816-1437 · K1437</span></div><time>剛剛</time></div>":"")+"<div class='recent-item'><div class='recent-avatar'>何</div><div><strong>何雨晴 · 3 人</strong><span>KP-816-1431 · K1431</span></div><time>14:16</time></div><div class='recent-item'><div class='recent-avatar'>吳</div><div><strong>吳凱琳 · 1 人</strong><span>KP-816-1430 · K1430</span></div><time>14:14</time></div><div class='recent-item'><div class='recent-avatar'>張</div><div><strong>張語芯 · 2 人</strong><span>已完成入場</span></div><time>14:11</time></div></div></article><article class='panel table-panel'><div class='panel-head'><div><h2>今日場次</h2><p>預約容量、報到與入場進度</p></div><button class='panel-link' data-view='sessions'>完整監測 →</button></div><table class='data-table'><thead><tr><th>時段</th><th>場次</th><th>預約</th><th>報到</th><th>入場</th><th>容量</th><th>狀態</th><th></th></tr></thead><tbody>"+sessionRows()+"</tbody></table></article></div></section>");}
  function sessionsView(){syncRoster();var data=stored(),checked=data.status==="checked-in"||data.status==="called";return layout("<section class='staff-content'>"+pageHead("SESSION MONITOR","場次監測","每一場以 50 人為容量上限；目前場次可直接進入掃碼或查看預約名單。")+"<div class='session-grid'>"+sessions.map(function(s){var isCurrent=s.status==="current";return "<article class='session-card "+(isCurrent?"current":"")+"'><div class='session-card-top'><p class='kicker'>"+s.label+"</p>"+pill(s.status)+"</div><h2>"+s.time+"—"+(s.time==="14:00"?"14:30":"下一時段")+"</h2><p>新光三越台北南西店 7F · 入口 A</p><div class='mini-metrics'><div><small>預約</small><b>"+s.booked+"</b></div><div><small>報到</small><b>"+(isCurrent&&checked?s.checked+1:s.checked)+"</b></div><div><small>入場</small><b>"+s.entered+"</b></div></div><button class='btn "+(isCurrent?"btn-dark":"btn-outline")+"' data-view='"+(isCurrent?"scanner":"roster")+"'>"+(isCurrent?"掃描本場預約 →":"查看名單 →")+"</button></article>";}).join("")+"</div></section>");}
  function rosterView(){syncRoster();var q=state.filter.toLowerCase();var rows=roster.filter(function(r){return (!q||r.name.indexOf(q)>-1||r.code.toLowerCase().indexOf(q)>-1)&& (state.statusFilter==="all"||r.status===state.statusFilter);});return layout("<section class='staff-content'>"+pageHead("RESERVATION ROSTER","預約與報到名單","可依姓名或預約碼搜尋；遇到無法掃描時，可由工作人員人工核對處理。")+"<div class='filters'><input id='roster-search' class='search' placeholder='搜尋姓名或預約代碼' value='"+state.filter+"'><select id='status-filter' class='filter-select'><option value='all'>全部狀態</option><option value='reserved' "+(state.statusFilter==="reserved"?"selected":"")+">已預約</option><option value='checked-in' "+(state.statusFilter==="checked-in"?"selected":"")+">已報到</option><option value='entered' "+(state.statusFilter==="entered"?"selected":"")+">已入場</option></select></div><div class='roster-table'><table class='data-table'><thead><tr><th>預約者</th><th>預約代碼</th><th>時段</th><th>人數</th><th>叫號</th><th>狀態</th><th></th></tr></thead><tbody>"+rows.map(function(r){return "<tr><td><div class='holder-cell'><div class='recent-avatar'>"+r.name.slice(0,1)+"</div><div><strong>"+r.name+"</strong><span style='display:block;color:#777;margin-top:4px'>"+r.phone+"</span></div></div></td><td>"+r.code+"</td><td><strong>"+r.slot+"</strong></td><td>"+r.party+" 人</td><td>"+r.queue+"</td><td>"+pill(r.status)+"</td><td><button class='text-btn' data-scan-code='"+r.code+"'>核對 →</button></td></tr>";}).join("")+"</tbody></table></div></section>");}
  function qr(seed){var out="";function f(x,y,ox,oy){var dx=x-ox,dy=y-oy;return dx>=0&&dy>=0&&dx<=6&&dy<=6&&(dx===0||dy===0||dx===6||dy===6||(dx>=2&&dx<=4&&dy>=2&&dy<=4));}for(var y=0;y<21;y++){for(var x=0;x<21;x++){var finder=f(x,y,0,0)||f(x,y,14,0)||f(x,y,0,14),n=((x*17+y*29+seed*13+x*y*7)%11)<5;out+="<i class='"+(finder||(n&&!((x<8&&y<8)||(x>12&&y<8)||(x<8&&y>12)))?"on":"")+"'></i>";}}return "<div class='staff-qr'>"+out+"</div>";}
  function scanResult(){if(state.scanStep==="idle")return "<div class='empty-result'><i>⌗</i><strong>等待掃描預約 QR</strong><span>掃描結果與核對資料將顯示在這裡</span></div>";if(state.scanStep==="success")return "<div class='success-result'><i>✓</i><h2>報到成功</h2><p>預約狀態已同步至使用者手機與現場叫號系統。</p><div class='assigned'><small>ASSIGNED QUEUE NUMBER</small><strong>K1437</strong><span>前方 7 組 · 預估等待 12—18 分鐘</span></div><button class='btn btn-primary btn-block' data-action='next-scan'>掃描下一位</button></div>";var data=stored();return "<div class='result-head'><div><p class='kicker' style='color:var(--acid)'>VALID RESERVATION</p><h2>確認預約資料</h2></div>"+pill("checked-in")+"</div><div class='result-event'>"+art()+"<div><strong>BABYMONSTER<br>POP-UP STORE</strong><span>TDK Culture · 台北南西店 7F</span></div></div><div class='verify-list'><div class='verify-row'><span>預約時段</span><strong>08/15（六）14:00—14:30</strong></div><div class='verify-row'><span>主預約人</span><strong>"+(data.holder||"林星妍")+"</strong></div><div class='verify-row'><span>入場人數</span><strong>"+((Number(data.companions)||1)+1)+" 人</strong></div><div class='verify-row'><span>手機末碼</span><strong>••• 5678</strong></div><div class='verify-row'><span>預約代碼</span><strong>KP-816-1437</strong></div></div><div class='valid-rule'><i>✓</i><div><strong>符合目前可報到場次</strong><span>目前開放：14:00—14:30</span></div></div><div class='result-actions'><button class='btn btn-outline' data-action='reject-scan'>取消</button><button class='btn btn-primary' data-action='confirm-checkin'>確認 "+((Number(data.companions)||1)+1)+" 人報到</button></div>";}
  function scannerView(){return layout("<section class='staff-content'>"+pageHead("QR CHECK-IN","掃描預約 QR","掃描後先核對活動、時段、狀態與整組人數，再完成報到並產生現場叫號。")+"<div class='scanner-layout'><article class='panel scanner-panel'><div class='scanner-header'><h2>入口 A · 相機掃描</h2><p>將使用者手機上的 QR Code 放入框內</p></div><div class='camera'><div class='camera-card'><strong>BABYMONSTER</strong>"+qr(7)+"<span>KP-816-1437</span></div><div class='scan-frame'><i></i><i></i><i></i><i></i><b></b></div><div class='camera-controls'><button class='camera-tool'>⌁ 手電筒</button><button class='scan-button' data-action='scan'>SCAN</button><button class='camera-tool'>⌨ 輸入代碼</button></div></div></article><aside class='panel scan-result'>"+scanResult()+"</aside></div></section>");}
  function queueView(){syncRoster();var list=roster.filter(function(r){return r.status==="checked-in"||r.status==="called";});return layout("<section class='staff-content'>"+pageHead("LIVE QUEUE CONTROL","現場叫號控制","目前場次 14:00—14:30；叫號狀態會同步到使用者手機與現場大螢幕。")+"<div class='queue-control'><article class='panel calling-panel'><p class='kicker'>NOW CALLING · 入口 A</p><div class='calling-number'>"+state.now+"</div><div class='calling-actions'><button class='btn btn-dark' data-action='recall'>再次叫號</button><button class='btn btn-pink' data-action='next-call'>下一組 →</button></div></article><aside class='panel queue-side'><div class='panel-head'><div><h2>候位隊列</h2><p>依報到時間排序</p></div><span class='pill pill-green'>"+list.length+" 組候位</span></div><div class='next-list'>"+list.map(function(r,i){return "<div class='next-item'><b>"+r.queue+"</b><div><strong>"+r.name+" · "+r.party+" 人</strong><span>報到 "+(i?"14:"+(14+i*2):"14:14")+"</span></div>"+pill(r.status)+"</div>";}).join("")+"</div><button class='btn btn-outline btn-block' data-view='roster'>人工搜尋預約</button></aside></div></section>");}
  function render(){var views={dashboard:dashboard,sessions:sessionsView,roster:rosterView,scanner:scannerView,queue:queueView};app.innerHTML=(views[state.view]||dashboard)();if(state.view==="sessions"){var ends={"11:00":"11:30","12:30":"13:00","14:00":"14:30","14:30":"15:00","15:00":"15:30","15:30":"16:00"};document.querySelectorAll(".session-card h2").forEach(function(el,index){el.textContent=sessions[index].time+"—"+ends[sessions[index].time];});}}
  document.addEventListener("click",function(e){var toggle=e.target.closest("[data-action='toggle-theme']");if(!toggle)return;e.preventDefault();e.stopImmediatePropagation();applyTheme(state.theme==="light"?"dark":"light");toggle.remove();syncThemeControl();toast(state.theme==="light"?"已切換為亮色模式":"已切換為暗色模式");},true);
  document.addEventListener("click",function(e){var view=e.target.closest("[data-view]"),action=e.target.closest("[data-action]"),code=e.target.closest("[data-scan-code]");if(view){state.view=view.dataset.view;render();return;}if(code){state.view="scanner";state.scanStep="review";render();return;}if(!action)return;var type=action.dataset.action;if(type==="scan"){state.scanStep="review";toast("已讀取預約 KP-816-1437");render();}else if(type==="reject-scan"){state.scanStep="idle";render();}else if(type==="confirm-checkin"){persist({status:"checked-in",queue:"K1437",now:state.now,checkedInAt:"14:18"});state.scanStep="success";toast("報到完成，已建立叫號 K1437");render();}else if(type==="next-scan"){state.scanStep="idle";render();}else if(type==="recall"){toast("已再次播報 "+state.now);}else if(type==="next-call"){state.now=state.now==="K1429"?"K1430":state.now==="K1430"?"K1431":"K1437";if(state.now==="K1437")persist({status:"called",queue:"K1437",now:"K1437"});toast("現場叫號已更新為 "+state.now);render();}});
  document.addEventListener("input",function(e){if(e.target.id==="roster-search"){state.filter=e.target.value;rosterViewDebounced();}});document.addEventListener("change",function(e){if(e.target.id==="status-filter"){state.statusFilter=e.target.value;render();}});var timer;function rosterViewDebounced(){clearTimeout(timer);timer=setTimeout(render,160);}
  var themeObserver=new MutationObserver(syncThemeControl);themeObserver.observe(app,{childList:true});applyTheme(state.theme,false);window.addEventListener("storage",function(e){if(e.key===THEME_STORAGE){applyTheme(e.newValue||"dark",false);var toggle=document.querySelector(".theme-toggle");if(toggle)toggle.remove();syncThemeControl();}else render();});window.addEventListener("focus",function(){render();});render();syncThemeControl();
}());
