(function(){
  "use strict";
  var app=document.getElementById("user-app");
  var toastEl=document.getElementById("user-toast");
  var STORAGE="airesv-babymonster-demo";
  var state={screen:new URLSearchParams(location.search).get("screen")||"home",date:"08/15",slot:"14:00",companions:1,holder:"林星妍",phone:"0912 345 678",status:"none",queue:"K1437",now:"K1429"};

  function stored(){try{return JSON.parse(localStorage.getItem(STORAGE)||"{}");}catch(e){return {};}}
  function persist(patch){var data=Object.assign({},stored(),patch,{updatedAt:Date.now()});localStorage.setItem(STORAGE,JSON.stringify(data));return data;}
  function toast(text){toastEl.textContent=text;toastEl.classList.add("show");setTimeout(function(){toastEl.classList.remove("show");},1800);}
  function statusBar(){return "<div class='user-status'><span>9:41</span><span>5G ▰</span></div>";}
  function brand(){return "<div class='brand-lockup'><div class='bm-art'><b>BM</b><i></i></div><div><strong>BABYMONSTER</strong><span>TDK Culture · 台北南西 7F</span></div></div>";}
  function header(title,back){return statusBar()+"<header class='user-header'>"+(back?"<button class='icon-btn' data-go='"+back+"' aria-label='返回'>‹</button>":brand())+(back?"<div class='user-head-title'>"+title+"</div>":"")+"<button class='icon-btn' data-action='reset' aria-label='更多'>••</button></header>";}
  function tabs(active){return "<nav class='user-tabbar'><button class='"+(active==="home"?"active":"")+"' data-go='home'><b>01</b>探索</button><button class='"+(active==="ticket"?"active":"")+"' data-go='ticket'><b>02</b>預約</button><button class='"+(active==="queue"?"active":"")+"' data-go='queue'><b>03</b>叫號</button><button class='"+(active==="info"?"active":"")+"' data-go='info'><b>04</b>資訊</button></nav>";}
  function qr(seed){var out="";function finder(x,y,ox,oy){var dx=x-ox,dy=y-oy;return dx>=0&&dy>=0&&dx<=6&&dy<=6&&(dx===0||dy===0||dx===6||dy===6||(dx>=2&&dx<=4&&dy>=2&&dy<=4));}for(var y=0;y<21;y++){for(var x=0;x<21;x++){var f=finder(x,y,0,0)||finder(x,y,14,0)||finder(x,y,0,14);var n=((x*17+y*29+seed*13+x*y*7)%11)<5;var on=f||(n&&!((x<8&&y<8)||(x>12&&y<8)||(x<8&&y>12)));out+="<i class='"+(on?"on":"")+"'></i>";}}return "<div class='qr' aria-label='預約 QR Code'>"+out+"</div>";}
  function shell(content,bottom){return "<section class='user-screen'>"+content+(bottom||"")+"</section>";}
  function home(){return shell(header("","")+"<div class='user-scroll'><section class='user-hero'><p class='kicker'>BABYMONSTER POP-UP STORE · TAIPEI</p><h1>BABY<em>MONSTER</em></h1><div class='hero-details'><span><b>2026.08.15—08.24</b></span><span>新光三越台北南西店 · 7F</span><span>主辦單位 · TDK Culture</span><span>每日 11:00—20:00</span></div><div class='hero-disc'>TDK<br>CULTURE<br>TAIPEI</div></section><section class='home-copy'><div class='home-copy-head'><h2>入場預約</h2><span>每時段 50 人</span></div><p>選擇到店時段，完成手機驗證即可取得專屬 QR Code。抵達後由入口工作人員掃描報到，再於手機查看即時叫號。</p></section></div><div class='user-bottom'><button class='btn btn-primary btn-block' data-go='slots'>選擇預約時段 →</button></div>"+tabs("home"));}
  function slots(){var items=[["11:00","上午場","36 / 50",false],["12:30","午間場","已額滿",true],["14:00","午後場","19 / 50",false],["15:30","午後場","42 / 50",false],["17:00","傍晚場","8 / 50",false]];return shell(header("選擇時段","home")+"<div class='user-scroll'><section class='screen-head'><p class='kicker'>STEP 01 / 03</p><h1>選一個到店時段</h1><p>預約成功即保留名額；現場叫號順序依實際掃碼報到時間產生。</p></section><div class='date-row'><button class='date-btn'><span>五</span><b>14</b></button><button class='date-btn active'><span>六</span><b>15</b></button><button class='date-btn'><span>日</span><b>16</b></button><button class='date-btn'><span>一</span><b>17</b></button><button class='date-btn'><span>二</span><b>18</b></button></div><div class='slot-list'>"+items.map(function(i){return "<button class='slot "+(state.slot===i[0]?"active ":"")+(i[3]?"full":"")+"' data-slot='"+i[0]+"' "+(i[3]?"disabled":"")+"><strong>"+i[0]+"</strong><div><b>"+i[1]+" · 30 分鐘</b><span>新光三越台北南西店 7F</span></div><span>"+i[2]+"</span></button>";}).join("")+"</div><div class='selection-summary'><span>已選擇 <b>08/15 "+state.slot+"</b></span><span>預約 2 人</span></div></div><div class='user-bottom'><button class='btn btn-primary btn-block' data-go='form'>填寫預約資料 →</button></div>");}
  function form(){return shell(header("預約資料","slots")+"<div class='user-scroll'><section class='screen-head'><p class='kicker'>STEP 02 / 03</p><h1>完成實名預約</h1><p>主預約人完成手機驗證；同行者不需個別驗證，但需一同入場。</p></section><form class='form-card' id='booking-form'><div class='form-summary'><b>15</b><div><strong>08/15（六）"+state.slot+"—"+(state.slot==="14:00"?"14:30":"下一時段")+"</strong><span>BABYMONSTER · 台北南西店 7F</span></div></div><div class='field'><label>主預約人姓名</label><input name='holder' value='"+state.holder+"' required></div><div class='field'><label>手機號碼</label><input name='phone' value='"+state.phone+"' inputmode='tel' required></div><div class='field'><label>SMS 驗證碼</label><input class='otp-input' value='8164' inputmode='numeric' required></div><div class='party-row'><div><b>同行者</b><small>最多可帶 2 位</small></div><div class='stepper'><button type='button' data-step='minus'>−</button><span>"+state.companions+"</span><button type='button' data-step='plus'>＋</button></div></div><div class='consent'><i></i><span>我同意活動規則與個人資料使用說明，並確認同行者將與我同時入場。</span></div><button class='btn btn-primary btn-block' type='submit'>確認預約並取得 QR</button></form></div>");}
  function ticket(){var data=stored();var status=data.status||state.status;return shell(header("我的預約","home")+"<div class='user-scroll'><div class='booking-title'><h1>"+(status==="none"?"尚未預約":"預約成功")+"</h1><span class='pill "+(status==="checked-in"?"pill-dark":"pill-green")+"'>"+(status==="checked-in"?"已報到":"已預約")+"</span></div><article class='ticket'><div class='ticket-top'><p class='kicker'>TDK CULTURE · ADMISSION PASS</p><h2>BABYMONSTER</h2><p>POP-UP STORE · TAIPEI NANXI</p></div><div class='ticket-body'><div class='ticket-data'><div><small>DATE / TIME</small><strong>08.15 SAT<br>"+(data.slot||state.slot)+"—14:30</strong></div><div><small>PARTY</small><strong>"+((data.companions||state.companions)+1)+" PEOPLE</strong></div><div><small>HOLDER</small><strong>"+(data.holder||state.holder)+"</strong></div></div><div class='qr-code'>"+qr(7)+"<span>KP-816-1437</span></div></div></article><div class='qr-note'><i>⌗</i><div><b>抵達後出示此 QR</b><br>請勿自行掃描；由入口工作人員完成報到。</div></div><div class='booking-actions'><button class='btn btn-outline' data-action='cancel'>取消預約</button><button class='btn btn-primary' data-go='arrival'>我已抵達現場 →</button></div></div>"+tabs("ticket"));}
  function arrival(){return shell(header("現場報到","ticket")+"<div class='user-scroll'><section class='screen-head'><p class='kicker'>ON-SITE / CHECK-IN</p><h1>把 QR 出示給工作人員</h1><p>前往入口 A，保持手機亮度，同行者請全員到齊。</p></section><section class='arrival-card'><p class='kicker' style='color:var(--acid)'>CURRENT WINDOW</p><h2>14:00—14:30</h2><p>目前可接受本場預約報到。工作人員將確認場次、預約狀態與整組人數。</p></section><div class='arrival-qr'>"+qr(7)+"</div><div class='scan-demo'><strong>等待工作人員掃描</strong><span>預約代碼 KP-816-1437 · 2 人</span></div><p class='arrival-help'>提案操作：可在另一個分頁開啟工作人員端並掃描此預約；或按下方按鈕直接模擬完成報到。</p></div><div class='user-bottom'><button class='btn btn-primary btn-block' data-action='self-checkin'>模擬工作人員完成掃描</button></div>");}
  function queue(){var data=stored();if(data.status!=="checked-in"&&data.status!=="called"){return shell(header("即時叫號","ticket")+"<div class='user-scroll'><section class='screen-head'><p class='kicker'>LIVE QUEUE</p><h1>尚未完成現場報到</h1><p>請先前往入口 A 出示預約 QR，由工作人員掃描後才會取得現場叫號。</p></section><div style='padding:0 18px'><button class='btn btn-primary btn-block' data-go='arrival'>前往報到說明 →</button></div></div>"+tabs("queue"));}if(data.status==="called"){return called();}return shell(header("即時叫號","ticket")+"<div class='user-scroll'><section class='queue-hero'><small>YOUR QUEUE NUMBER</small><div class='queue-id'>"+(data.queue||state.queue)+"</div><div class='queue-stats'><div><span>目前叫號</span><b>"+(data.now||state.now)+"</b></div><div><span>前方還有</span><b class='pink'>7 組</b></div></div></section><section class='progress-card'><div class='progress-head'><div><span>現場進度</span><strong>等待中</strong></div><span class='pill pill-green'>已報到</span></div><div class='progress-track'><i></i></div><div class='progress-labels'><span>K1429</span><span>預估 12—18 分鐘</span><span>K1437</span></div></section><section class='queue-timeline'><div class='timeline-row done'><i></i><b>完成預約</b><span>08/12 21:08</span></div><div class='timeline-row done'><i></i><b>入口掃碼報到</b><span>13:42</span></div><div class='timeline-row'><i></i><b>等待叫號</b><span>現在</span></div><div class='timeline-row'><i></i><b>前往入口 A</b><span>尚未</span></div></section><div style='padding:0 16px 18px'><button class='btn btn-primary btn-block' data-action='call-me'>提案示範：模擬叫到我</button></div></div>"+tabs("queue"));}
  function called(){return "<section class='called-screen'>"+header("","queue")+"<main class='called-main'><div class='called-burst'>NOW</div><h1>輪到你了<em>K1437</em></h1><p>請備妥手機上的預約 QR Code，與同行者一起前往入口。逾時將改列過號。</p><div class='entrance'><div><small>PLEASE GO TO</small><strong>入口 A · ADMISSION</strong></div><div><small>保留時間</small><b>08:42</b></div></div><button class='btn btn-primary btn-block' data-go='ticket'>開啟我的 QR Code</button></main></section>";}
  function info(){var products=[
    {name:"DRIP PHOTOBOOK ALBUM",meta:"1ST FULL ALBUM",price:"NT$ 890",tone:"album"},
    {name:"OFFICIAL LIGHT STICK",meta:"LIMITED POP-UP EDITION",price:"NT$ 1,690",tone:"light",sold:true},
    {name:"MEMBER PHOTO CARD SET",meta:"7 MEMBERS · RANDOM",price:"NT$ 490",tone:"cards",sold:true},
    {name:"MONSTER HOODIE",meta:"BLACK / M—XL",price:"NT$ 1,980",tone:"hoodie",tag:"LOW STOCK"},
    {name:"ACRYLIC KEYRING",meta:"CHARACTER SERIES",price:"NT$ 390",tone:"keyring"},
    {name:"POP-UP TOTE BAG",meta:"TAIPEI EXCLUSIVE",price:"NT$ 690",tone:"tote"}
  ];return shell(header("活動資訊","home")+"<div class='user-scroll info-scroll'>"+
    "<section class='info-hero'><div class='info-label'>POP-UP GUIDE · 2026</div><div class='info-monogram'><span>BA</span><span>BY</span><span>MON</span><span>STER</span></div><div class='info-hero-meta'><b>08.15—08.24</b><span>TAIPEI NANXI · 7F</span></div><div class='info-orbit'>TDK<br>CULTURE</div></section>"+
    "<section class='info-intro'><p class='kicker'>BABYMONSTER POP-UP STORE</p><h1>來店前，<br>先看這一頁。</h1><p>活動時間、入場提醒、專輯影音與現場商品庫存，集中在同一個資訊頁。</p></section>"+
    "<section class='info-block venue-block'><div class='info-section-head'><span>01</span><div><small>VISIT INFORMATION</small><h2>快閃店資訊</h2></div></div><div class='venue-grid'><div><small>活動日期</small><b>2026.08.15—08.24</b></div><div><small>營業時間</small><b>每日 11:00—20:00</b></div><div class='venue-wide'><small>地點</small><b>新光三越台北南西店 7F</b><span>台北市中山區南京西路 12 號 · 捷運中山站</span></div></div><a class='info-link' target='_blank' rel='noopener' href='https://www.google.com/maps/search/?api=1&query=%E6%96%B0%E5%85%89%E4%B8%89%E8%B6%8A%E5%8F%B0%E5%8C%97%E5%8D%97%E8%A5%BF%E5%BA%97'>在地圖中開啟 <b>↗</b></a></section>"+
    "<section class='notice-card'><div class='notice-mark'>!</div><div><p class='kicker'>BEFORE YOU COME</p><h2>入場注意事項</h2><ol><li>依預約時段提前 10 分鐘抵達，出示手機中的預約 QR Code。</li><li>QR Code 由入口工作人員掃描；請勿轉傳，重複使用將無法報到。</li><li>主預約人與同行者須同時到齊，逾時依現場候位狀況安排。</li><li>拍攝規範與商品庫存以現場公告為準。</li></ol></div></section>"+
    "<section class='info-block music-block'><div class='info-section-head'><span>02</span><div><small>ALBUM & MUSIC</small><h2>BABYMONSTER 音樂</h2></div></div><div class='album-feature'><div class='album-art'><i>1ST<br>FULL<br>ALBUM</i><strong>DRIP</strong><em>BM</em></div><div class='album-copy'><span>2024.11.01 · 9 TRACKS</span><h3>DRIP</h3><p>首張正規專輯以雙主打〈DRIP〉與〈CLIK CLAK〉揭開序幕，在嘻哈、EDM 與成員聲線之間呈現多樣面貌。</p><div class='track-tags'><i>DRIP</i><i>CLIK CLAK</i><i>BILLIONAIRE</i><i>LOVE IN MY HEART</i></div></div></div><div class='mv-row'><a class='mv-card mv-drip' target='_blank' rel='noopener' href='https://ygfamily.com/ko/artists/babymonster/discography/1614'><div class='mv-play'>▶</div><small>OFFICIAL MUSIC VIDEO</small><b>DRIP</b><span>前往官方影音 ↗</span></a><a class='mv-card mv-sheesh' target='_blank' rel='noopener' href='https://ygfamily.com/en/artists/babymonster/discography/1594'><div class='mv-play'>▶</div><small>OFFICIAL MUSIC VIDEO</small><b>SHEESH</b><span>前往官方影音 ↗</span></a></div></section>"+
    "<section class='info-block merch-block'><div class='info-section-head'><span>03</span><div><small>POP-UP HIGHLIGHTS</small><h2>商品重點</h2></div></div><div class='merch-note'><i></i><span>DEMO 庫存快訊 · 16:10 更新</span></div><div class='merch-grid'>"+products.map(function(p){return "<article class='merch-card "+(p.sold?"is-sold ":"")+"'><div class='merch-visual "+p.tone+"'><span>BM</span>"+(p.sold?"<strong>已售完</strong>":p.tag?"<strong class='low'>"+p.tag+"</strong>":"")+"</div><small>"+p.meta+"</small><h3>"+p.name+"</h3><b>"+p.price+"</b></article>";}).join("")+"</div><p class='demo-disclaimer'>商品、售價及庫存狀態為提案情境模擬，正式內容以主辦單位與現場公告為準。</p></section>"+
    "<footer class='info-footer'><b>TDK CULTURE</b><span>BABYMONSTER POP-UP STORE · TAIPEI</span></footer></div>"+tabs("info"));}
  function render(){var views={home:home,slots:slots,form:form,ticket:ticket,arrival:arrival,queue:queue,called:called,info:info};app.innerHTML=(views[state.screen]||home)();}

  document.addEventListener("click",function(e){var go=e.target.closest("[data-go]"),slot=e.target.closest("[data-slot]"),step=e.target.closest("[data-step]"),action=e.target.closest("[data-action]");if(go){state.screen=go.dataset.go;render();return;}if(slot){state.slot=slot.dataset.slot;render();return;}if(step){state.companions=Math.max(0,Math.min(2,state.companions+(step.dataset.step==="plus"?1:-1)));render();return;}if(!action)return;var type=action.dataset.action;if(type==="self-checkin"){persist({status:"checked-in",queue:"K1437",now:"K1429",checkedInAt:"13:42"});state.screen="queue";toast("報到完成，已取得叫號 K1437");render();}else if(type==="call-me"){persist({status:"called",queue:"K1437",now:"K1437"});state.screen="called";render();}else if(type==="cancel"){persist({status:"cancelled"});state.screen="home";toast("示範預約已取消");render();}else if(type==="reset"){localStorage.removeItem(STORAGE);state.screen="home";state.status="none";toast("示範資料已重設");render();}});
  document.addEventListener("submit",function(e){if(e.target.id!=="booking-form")return;e.preventDefault();var form=new FormData(e.target);state.holder=form.get("holder")||state.holder;state.phone=form.get("phone")||state.phone;state.status="reserved";persist({status:"reserved",code:"KP-816-1437",holder:state.holder,phone:state.phone,slot:state.slot,companions:state.companions,queue:null});state.screen="ticket";toast("預約成功，QR Code 已建立");render();});
  window.addEventListener("storage",function(){var d=stored();if(d.status==="checked-in"&&state.screen==="arrival"){state.screen="queue";toast("工作人員已完成報到");render();}else if(d.status==="called"&&(state.screen==="queue"||state.screen==="arrival")){state.screen="called";render();}else{render();}});
  window.addEventListener("focus",function(){var d=stored();if(d.status==="checked-in"&&state.screen==="arrival"){state.screen="queue";toast("工作人員已完成報到");render();}});
  render();
}());
